"""Config module"""

PLAYER_WIDTH  = 40
PLAYER_HEIGHT = 40
PLAYER_SPEED  =  4

NPC_SPEED  =  2

SCREEN_WIDTH  = 800
SCREEN_HEIGHT = 600

GAME_FPS = 50
CLIENT_REFRESH_COEF = 1
INFO_TIMER = 1

BULLET_SPEED = 5
BULLET_SIZE = 5

GATEWAY_ADDRESS = 'https://drsnyjelen.cz'
#GATEWAY_ADDRESS = "http://localhost:3333"
